### ISSUE TITLE
Please fix type-o

### ISSUE THREAD

**Issue by NamooDrood** [r1ft4469/broker_orderhall#1]
Hello,
I really like your addon, but please fix the spelling error in line 265 of broker_orderhall.lua:

Wrong:
self:AddDoubleLine("|cFFFFE000"..info.name..":", "|cFF00FF00Compleated",1,1,1, 1,1,1)
Correct:
self:AddDoubleLine("|cFFFFE000"..info.name..":", "|cFF00FF00Completed",1,1,1, 1,1,1)

Thank you very much!
Namoo

**Comment by r1ft4469** [comment]
Thank you so much its been fixed and should be on curse in the next few minutes.
